/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ilyanemtsov
 */
public class CashPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentPanel
     */
    public CashPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tenderedAmountLabel = new javax.swing.JLabel();
        tenderedAmountTextArea = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(400, 150));

        tenderedAmountLabel.setText("Tendered Amount: $");

        tenderedAmountTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenderedAmountTextAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tenderedAmountLabel)
                .addGap(18, 18, 18)
                .addComponent(tenderedAmountTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenderedAmountLabel)
                    .addComponent(tenderedAmountTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tenderedAmountTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenderedAmountTextAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenderedAmountTextAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel tenderedAmountLabel;
    private javax.swing.JTextField tenderedAmountTextArea;
    // End of variables declaration//GEN-END:variables
}
