/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ilyanemtsov
 */
public class CheckPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentPanel
     */
    public CheckPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckRoutingNumberLabel = new javax.swing.JLabel();
        CheckRoutingTextArea = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(400, 150));

        CheckRoutingNumberLabel.setText("Check Routing # :");

        CheckRoutingTextArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckRoutingTextAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(CheckRoutingNumberLabel)
                .addGap(18, 18, 18)
                .addComponent(CheckRoutingTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckRoutingNumberLabel)
                    .addComponent(CheckRoutingTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CheckRoutingTextAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckRoutingTextAreaActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_CheckRoutingTextAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CheckRoutingNumberLabel;
    private javax.swing.JTextField CheckRoutingTextArea;
    // End of variables declaration//GEN-END:variables
}
